<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Ticket Details</title>
</head>

<body>
<div align="center" width="100%" border="2px">
    <div align="center" valign="top">
        <br> <br>
        <div width="600" border="3px">

            <div style="font-size: 48px; color:black; font-family: Arial;">
                <b>Ticket Details</b>
            </div>

            <div style="font-size: 24px; color: black;">
                <br>  <b>Your Payment Has Been Successfully Processed</b> <br>
            </div>

            <div>
                <br> Dear ${fullName}, thank you for choosing CinemaHub for purchasing your ticket.<br>
                <br>
                <h3>Ticket Details</h3>
                <h4>${movieName}</h4>
                <br>
                <h5><b>Date: </b> ${movieDay} </h5>
                <h5><b>Cinema: </b> ${saloonName} </h5>
                <h5><b>Session: </b> ${movieStartTime} </h5>
                <h5><b>Seat: </b> ${chairNumbers} </h5>

            </div>
            <br>
            <div>
                <h4>We wish you a pleasant viewing, from the CineVision family.</h4>
            </div>
        </div>

        <br> <br>

    </div>
</div>
</body>
</html>