server:
  port: 0
spring:
  application:
    name: user-service
  ## MongoDB Properties
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: user
      port: 27017
      host: localhost
      auto-index-creation: true
  ## Zipkin and Sleuth Properties
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

## Eureka Properties
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# JWT properties
jwt:
  secret:
    key: subscribe_to_my_only_fans_UwU